name: Restart Bot Server

on:
    push:
        branches:
            - main
        paths: 
            - "src/**"
            - ".forgejo/workflows/restart-server.yml"
            - "drizzle.config.ts"
            - "package.json"
            - "tsconfig.json"
    workflow_dispatch: 

jobs:
    restart-site-server:
        name: Restart Bot Server
        runs-on: node

        steps: 
            - uses: actions/checkout@v4

            - name: Restart Server
              uses: https://git.stefdp.com/Stef/restart-ptero-action@main
              with:
                PTERO_PANEL_URL: ${{ secrets.PTERO_PANEL_URL }}
                PTERO_PANEL_TOKEN: ${{ secrets.PTERO_PANEL_TOKEN }}
                PTERO_PANEL_SERVER_ID: ${{ secrets.PTERO_PANEL_SERVER_ID }}